@MethodsReturnNonnullByDefault @ParametersAreNonnullByDefault
package com.dtteam.dynamictreesplus.model.loader;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;