import me.modmuss50.mpp.ReleaseType

plugins {
    id 'java-library'
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.neoforged.gradle.userdev' version '7.0.170'
    id "me.modmuss50.mod-publish-plugin" version "0.8.4"
}

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

version = mod_version
group = mod_group_id

repositories {
    mavenLocal()
    exclusiveContent {
        forRepository {
            maven {
                url "https://cursemaven.com"
            }
        }
        filter {
            includeGroup "curse.maven"
        }
    }
    maven {
        url 'https://harleyoconnor.com/maven'
    }
    flatDir {
        dir("libs")
    }
}

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

//minecraft.accessTransformers.file rootProject.file('src/main/resources/META-INF/accesstransformer.cfg')
//minecraft.accessTransformers.entry public net.minecraft.client.Minecraft textureManager # textureManager

runs {

    configureEach {
        systemProperty 'forge.logging.markers', 'REGISTRIES'

        systemProperty 'forge.logging.console.level', 'debug'

        modSource project.sourceSets.main
    }

    client {
        systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
    }

    server {
        systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
        argument '--nogui'
    }

    gameTestServer {
        systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
    }

    data {
        arguments.addAll(
                '--mod', project.mod_id,
                '--all',
                '--output', file('src/generated/resources/').getAbsolutePath(),
                '--existing', file('src/main/resources/').getAbsolutePath(),
                "--existing-mod", "dynamictrees")
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

dependencies {
    implementation "net.neoforged:neoforge:${neo_version}"

    implementation 'curse.maven:dynamictrees-252818:7513464'
    //implementation 'com.dtteam.dynamictrees:dynamictrees-neoforge-1.21.1:1.6.0-BETA03'

    runtimeOnly 'curse.maven:jade-324717:6291517'
    runtimeOnly "curse.maven:jei-238222:5846880"

    runtimeOnly "curse.maven:glitchcore-955399:5660740"
    runtimeOnly "curse.maven:serene-seasons-291874:5753503"
    runtimeOnly "curse.maven:patchouli-306770:6164617"
}

tasks.withType(ProcessResources).configureEach {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_version,
            neo_version_range      : neo_version_range,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
            mod_authors            : mod_authors,
            mod_credits            : mod_credits,
            mod_description        : mod_description
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties
    }
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/repo"
        }
        var mavenUsername = project.findProperty("harleyOConnorMavenUsername")?.toString() ?: System.getenv("MAVEN_USERNAME")
        var mavenPassword = project.findProperty("harleyOConnorMavenPassword")?.toString() ?: System.getenv("MAVEN_PASSWORD")
        if (mavenUsername == null || mavenPassword == null) {
            logger.log(LogLevel.WARN,"Credentials for maven not detected; it will be disabled.")
            return
        }
        maven {
            name = "HarleyOConnor"
            url = "https://harleyoconnor.com/maven"
            credentials {
                username = mavenUsername
                password = mavenPassword
            }
        }
    }
}

def changelogFile = file("build/changelog.txt")

publishMods {
    file = jar.archiveFile
    displayName = "${mod_name.replace(' ','')}-${minecraft_version} ${mod_version}"
    if (changelogFile.exists()) {
        changelog.set(changelogFile.getText())
    }
    type = ReleaseType.of(version_type.toUpperCase())
    modLoaders.add("neoforge")

    curseforge {
        projectId = "478155"
        projectSlug = "dynamictreesplus" // Required for discord webhook
        accessToken = curseApiKey ?: System.getenv("CURSEFORGE_API_KEY")
        minecraftVersions.add("1.21.1")
        requires("dynamictrees")
    }
    modrinth {
        projectId = "qaO9Dqpu"
        accessToken = modrinthToken ?: System.getenv("MODRINTH_TOKEN")
        minecraftVersions.add("1.21.1")
        requires("vdjF5PL5")
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}

tasks.jar {
    manifest {
        archiveFileName.set("${project.name}-neoforge-${minecraft_version}-${project.version}.jar")
    }
}
