modName=DynamicTreesPlus
modId=dynamictreesplus
modVersion=1.2.2
group=com.ferreusveritas.dynamictreesplus

mcVersion=1.20.1
forgeVersion=47.4.0
mappingsChannel=parchment
mappingsVersion=2023.09.03-1.20.1

dynamicTreesVersion=1.4.2
jeiVersion=15.0.0.12
patchouliVersion=1.20.1-84-FORGE
suggestionProviderFixVersion=1.0.0
ccVersion=1.109.4
gcFileId=5787839
ssFileId=5790633
jadeFileId=4986594

versionType=release

# Path of update checker relative to version info file
updateCheckerPath=DynamicTreesPlus.json
# Set to true if this version should be marked as the recommended version on the update checker
versionRecommended=true

org.gradle.jvmargs=-Xmx6G
org.gradle.daemon=false