@MethodsReturnNonnullByDefault @ParametersAreNonnullByDefault
package com.ferreusveritas.dynamictreesplus.blocks;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;