@MethodsReturnNonnullByDefault @ParametersAreNonnullByDefault
package com.dtteam.dynamictreesplus.model.baked;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;