@MethodsReturnNonnullByDefault @ParametersAreNonnullByDefault
package com.dtteam.dynamictreesplus.model.geometry;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;